language: rust
sudo: false
os:
    - linux
    - osx
rust:
    - stable
    - nightly
jobs:
    include:
        - name: rustfmt
          before_install:
              - rustup component add rustfmt
              - cargo fmt --version
          script: cargo fmt --all -- --check

script:
    - cargo build -v && cargo test -v && cargo doc -v
