language: rust
sudo: false
os:
    - linux
    - osx
rust:
    - stable
    - nightly

before_install:
    - rustup component add rustfmt
    - cargo fmt --version

script:
    - cargo fmt --all -- --check
    - cargo build -v && cargo test -v && cargo doc -v
