[package]
name = "image-canvas"
version = "0.2.0"
edition = "2021"

[dependencies]
canvas = { path = "../texel", package = "image-texel" }

[dev-dependencies]
brunch = "0.2.5"

[[bench]]
name = "conversion"
path = "benchmarks/conversion.rs"
harness = false
