[package]
name = "image-framebuf"
version = "0.1.0"
edition = "2021"

[dependencies]
image-canvas = { path = "../" }

[dev-dependencies]
brunch = "0.2.5"

[[bench]]
name = "conversion"
path = "benchmarks/conversion.rs"
harness = false
